### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by gh0st** [michael-wolfenden/sqlops-theme-onedark#1]
Double clicking the installer `.vsix` produces this error.

> The install of 'Atom One Dark' was not successful for all the selected products. For more information, click on the install log link at the bottom of the dialog.

> This extension is not installable on any currently installed products.

Install log
```
2/8/2019 10:07:35 AM - Microsoft VSIX Installer
2/8/2019 10:07:35 AM - -------------------------------------------
2/8/2019 10:07:35 AM - vsixinstaller.exe version:
2/8/2019 10:07:35 AM - 15.9.3032
2/8/2019 10:07:35 AM - -------------------------------------------
2/8/2019 10:07:35 AM - Command line parameters:
2/8/2019 10:07:35 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\user\Downloads\sqlops-theme-onedark-1.0.0 (1).vsix
2/8/2019 10:07:35 AM - -------------------------------------------
2/8/2019 10:07:35 AM - Microsoft VSIX Installer
2/8/2019 10:07:35 AM - -------------------------------------------
2/8/2019 10:07:44 AM - Initializing Install...
2/8/2019 10:07:44 AM - Extension Details...
2/8/2019 10:07:44 AM - 	Identifier         : sqlops-theme-onedark
2/8/2019 10:07:44 AM - 	Name               : Atom One Dark
2/8/2019 10:07:44 AM - 	Author             : michael-wolfenden
2/8/2019 10:07:44 AM - 	Version            : 1.0.0
2/8/2019 10:07:44 AM - 	Description        : One Dark Theme based on Atom
2/8/2019 10:07:44 AM - 	Locale             : en-US
2/8/2019 10:07:44 AM - 	MoreInfoURL        : 
2/8/2019 10:07:44 AM - 	InstalledByMSI     : False
2/8/2019 10:07:44 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2/8/2019 10:07:44 AM - 
2/8/2019 10:07:44 AM - 	SignatureState     : Unsigned
2/8/2019 10:07:44 AM - 	Supported Products : 
2/8/2019 10:07:44 AM - 		Microsoft.VisualStudio.Code
2/8/2019 10:07:44 AM - 			Version : 
2/8/2019 10:07:44 AM - 
2/8/2019 10:07:44 AM - 	References         : 
2/8/2019 10:07:44 AM - Signature Details...
2/8/2019 10:07:44 AM - 	Extension is not signed.
2/8/2019 10:07:44 AM - 
2/8/2019 10:07:44 AM - Searching for applicable products...
2/8/2019 10:07:44 AM - Found installed product - Global Location
2/8/2019 10:07:44 AM - Found installed product - ssms
2/8/2019 10:07:44 AM - Found installed product - Visual Studio Enterprise 2017
2/8/2019 10:07:45 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by gh0st** [comment]
Guess I should read the instructions.

> can be installed by opening the command palette and selecting Extensions: Install from VSIX...
